### ISSUE TITLE
withdraw XDC from wallet

### ISSUE THREAD

**Issue by TK-2024-G** [myxdc/myxdc#2]
Hi Team,
I have XDC on MyXDC wallet - connect with My ledger live.
i tried to withdraw XDC, but it gave me the error.
Could you please help?
![send xdc - message error 6-18-24](https://github.com/myxdc/myxdc/assets/173640718/5120542c-6f7e-4b9f-8f82-21c910538094)

thanks

**Comment by TheLubab** [comment]
Hi, I'm happy to help. 

Did this error happen after you click sign in your ledger or before?

**Comment by TK-2024-G** [comment]
that happened before after I click send bottom from myxdc wallet, it gave me the error message right away.
please help.
thanks

**Comment by TK-2024-G** [comment]
Just to verify,
i have no problem sign in Ledger live , deposit or withdraw other coins is not problem at all.
i have no problem to sent XDC to myXDC wallet also.
the only problem i have when i tried to withdraw , it show error above and not let me process transaction.
please help.

i aslo tried to export my private key from myxdc wallet to add it into metamask wallet, but it did not allow me export at all.
thanks

**Comment by DApps-Github** [comment]
Hey there @TK-2024-G  ,

kindly refresh your wallet, if the issue persists, It means the backend systems went down as a result of transcript error. 
Your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live chat with the ticket ID XDC7463
 
Please see the link below to our dedicated support line: 
 [XDC Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

**Comment by TheLubab** [comment]
@TK-2024-G I have deployed a fix at app.myxdc.org . Can you try it and let me know if it's working.

**Comment by TK-2024-G** [comment]
when they asked me sign and send transaction, it done nothing after.
please help.
thanks

**Comment by TK-2024-G** [comment]
> @TK-2024-G I have deployed a fix at app.myxdc.org . Can you try it and let me know if it's working.

Hi Seka,
now the wallet does not show my balance, i could not do anything.
please help.
thanks

**Comment by TK-2024-G** [comment]
> > @TK-2024-G I have deployed a fix at app.myxdc.org . Can you try it and let me know if it's working.
> 
> Hi Seka, now the wallet does not show my balance, i could not do anything. please help. thanks

Guy,
the app is still not working, i do not see my balance .
please help

**Comment by TheLubab** [comment]
have you tried using https://betawallet.xinfin.network/#/wallet/access ?

**Comment by TK-2024-G** [comment]
I did try but I only see other wallets, not the XDC wallet is on your app (app.myxdc.org).

Also Since yesterday,  i do not see the balance on my wallet - aap.myxdc.org

please fix your app please.
thanks

**Comment by TK-2024-G** [comment]
now, i see my balance and tried to submit the transaction. it game me the message error:" Ledger device: internal error, please report (0x6f00).
please help

**Comment by TheLubab** [comment]
I'm really sorry for your troubles, but myxdc wasn't ready for production use and there was a disclaimer when you open it to not use it with large amount.

> This is an Alpha version of MyXDC and is still undergoing testing and development. Please be aware that there may be bugs, unfinished features, and other issues present. Use at your own risk and do not store large amounts of assets in the wallet. We appreciate your feedback and suggestions as we continue to improve and refine the product. Thank you for your support!

I've really tried everything i could to fix your issue but the cause is not with myxdc, but an update from the ledger company which doesn't allow blind signing and the xdc app itself. When I added support for ledger, it was according to [this example](https://github.com/XinFinOrg/XDC_LedgerCompanion/blob/9a90c2dfdf6264ff639a57b725ce23bf25ae608b/src/cli.js#L54)  with the `44'/550'/0/0/0` path, but now for some reason all xdc wallets changed it to `44'/550'/0'/0`.

So your funds are untouched and your wallet still exists in the `44'/550'/0/0/0` derivative path, but the [ledger xdc app ](https://github.com/LedgerHQ/app-xinfin ) doesn't let us access it, i'm really sorry but unless they update the app there is nothing i can do to help.

**Comment by TK-2024-G** [comment]
> I'm really sorry for your troubles, but myxdc wasn't ready for production use and there was a disclaimer when you open it to not use it with large amount.
> 
> > This is an Alpha version of MyXDC and is still undergoing testing and development. Please be aware that there may be bugs, unfinished features, and other issues present. Use at your own risk and do not store large amounts of assets in the wallet. We appreciate your feedback and suggestions as we continue to improve and refine the product. Thank you for your support!
> 
> I've really tried everything i could to fix your issue but the cause is not with myxdc, but an update from the ledger company which doesn't allow blind signing and the xdc app itself. When I added support for ledger, it was according to [this example](https://github.com/XinFinOrg/XDC_LedgerCompanion/blob/9a90c2dfdf6264ff639a57b725ce23bf25ae608b/src/cli.js#L54) with the `44'/550'/0/0/0` path, but now for some reason all xdc wallets changed it to `44'/550'/0'/0`.
> 
> So your funds are untouched and your wallet still exists in the `44'/550'/0/0/0` derivative path, but the [ledger xdc app ](https://github.com/LedgerHQ/app-xinfin) doesn't let us access it, i'm really sorry but unless they update the app there is nothing i can do to help.

thanks for get back to me
is there any way we adjust the path: 44'/550'/0/0/0 like Ledger live 44'/550'/0'/0?

**Comment by TheLubab** [comment]
>  is there any way we adjust the path: 44'/550'/0/0/0 like Ledger live 44'/550'/0'/0?

I'm not sure but I'm still researching and testing, I will get back to you if I found a solution.

**Comment by TK-2024-G** [comment]
> > is there any way we adjust the path: 44'/550'/0/0/0 like Ledger live 44'/550'/0'/0?
> 
> I'm not sure but I'm still researching and testing, I will get back to you if I found a solution.

PLEASE i really need your help.
that is my life saving. i do not know what i am going to do if l lost the fund!!!

**Comment by TheLubab** [comment]
@TK-2024-G I've found a solution to make it work, please try again at app.myxdc.org and let me know.

**Comment by TK-2024-G** [comment]
> @TK-2024-G I've found a solution to make it work, please try again at app.myxdc.org and let me know.

now the wallet app does not show my balance.
i could not do anything now.
i will try tomorrow and let you know.
thanks for get back to me.

**Comment by TK-2024-G** [comment]
> @TK-2024-G I've found a solution to make it work, please try again at app.myxdc.org and let me know.

Hi Sejaiking,
the app still not show my balance. i could not do anything.
PLease help

**Comment by TheLubab** [comment]
>  the app still not show my balance. i could not do anything.
 
Can you share a screenshot or more details, so i can see what's going on

**Comment by TK-2024-G** [comment]
> > the app still not show my balance. i could not do anything.
> 
> Can you share a screenshot or more details, so i can see what's going on

HI SeKaiking,
now it shows balance, i summited the send transaction, after I confirmed :"Review & send" . the MyXDC wallet app gave me message: "Returned error: zero gas price"
it did not send out the XDC after message.
![MESSAGE WHEN SUBMIT SEND TRANSACTION](https://github.com/myxdc/myxdc/assets/173640718/e8d41764-192a-4462-96fb-be582b39277f)
please help.
thanks

**Comment by TK-2024-G** [comment]
> HI SeKaiking, now it shows balance, i summited the send transaction, after I confirmed :"Review & send" . the MyXDC wallet app gave me message: "Returned error: zero gas price" it did not send out the XDC after message. 
-------
please note I have a lot XDC in MyXDC Wallet, I only tested to send out 304 XDC  but the message shows "Returned error: zero gas price".

the app does not gave me option to reset gas price.
Please help.
thanks

**Comment by TK-2024-G** [comment]
> > HI SeKaiking, now it shows balance, i summited the send transaction, after I confirmed :"Review & send" . the MyXDC wallet app gave me message: "Returned error: zero gas price" it did not send out the XDC after message.
> 
> please note I have a lot XDC in MyXDC Wallet, I only tested to send out 304 XDC but the message shows "Returned error: zero gas price".
> 
> the app does not gave me option to reset gas price. Please help. thanks

Hi Team, i am waiting your help.
thanks

**Comment by TheLubab** [comment]
Sorry for the late response. We fixed that now!

**Comment by TK-2024-G** [comment]
> Sorry for the late response. We fixed that now!

thanks Team,
My withdraw transaction was successful.
thanks so much

**Comment by TK-2024-G** [comment]
Hi Sekaiking
I have same issue with other XDc wallet on web. Could you please help?
or if you know someone could help, would you please direct me to?
thanks
